import { execFileSync } from "node:child_process";
import os from "node:os";
import path from "node:path";
import fs from "fs-extra";
import { afterEach, describe, expect, it } from "vitest";
import { scopeCssForPcf } from "../src/cssScope";

const repoRoot = path.resolve(import.meta.dirname, "..");
const fixtureDir = path.join(repoRoot, "test", "fixtures", "css-scope");
const tempDirs: string[] = [];

afterEach(async () => {
	await Promise.all(tempDirs.splice(0).map((dir) => fs.remove(dir)));
});

async function readFixture(name: string): Promise<string> {
	return fs.readFile(path.join(fixtureDir, name), "utf8");
}

async function makeTempDir(): Promise<string> {
	const dir = await fs.mkdtemp(path.join(os.tmpdir(), "create-ec-app-css-"));
	tempDirs.push(dir);
	return dir;
}

describe("scopeCssForPcf", () => {
	it("scopes root, universal, dark, normal, and complex selector lists", async () => {
		const output = scopeCssForPcf(await readFixture("basic.css"), "MyControl");
		const scope = '.pcf-shell-control[data-pcf-control="MyControl"]';

		expect(output).toContain(
			"Generated by create-ec-app. CSS selectors are scoped to this PCF control.",
		);
		expect(output).toContain(`${scope} {\n\t--brand: red;`);
		expect(output).toContain(`${scope}, ${scope} * {\n\tbox-sizing`);
		expect(output).toContain(`${scope}.dark`);
		expect(output).toContain(`${scope} .dark`);
		expect(output).toContain(`${scope}.dark .panel`);
		expect(output).toContain(`${scope} .dark .panel`);
		expect(output).toContain(`${scope} .button`);
		expect(output).toContain(`${scope} .card[data-label="a,b"]`);
		expect(output).toContain(`${scope} :is(.alpha, .beta)`);
	});

	it("scopes shadcn-like selectors without splitting nested commas", async () => {
		const output = scopeCssForPcf(
			await readFixture("shadcn-like.css"),
			"ChartHost",
		);
		const scope = '.pcf-shell-control[data-pcf-control="ChartHost"]';

		expect(output).toContain(`${scope} .group\\/button:is(:hover, :focus)`);
		expect(output).toContain(`${scope} .recharts-dot[stroke='#fff']`);
		expect(output).toContain(`${scope}.dark .menu`);
		expect(output).toContain(`${scope} .dark .menu`);
	});

	it("does not scope keyframe rules", async () => {
		const output = scopeCssForPcf(await readFixture("keyframes.css"), "Motion");
		const scope = '.pcf-shell-control[data-pcf-control="Motion"]';

		expect(output).toContain("@keyframes fade-in");
		expect(output).toContain("from {\n\t\topacity: 0;");
		expect(output).not.toContain(`${scope} from`);
		expect(output).toContain(`${scope} .animate-in`);
	});

	it("keeps already-scoped selectors and maps app root aliases to the host", () => {
		const output = scopeCssForPcf(
			`.pcf-shell-control[data-pcf-control="Existing"] .button { color: red; }
:host, [data-ec-app-root], .ec-app[data-mode="x"] { color: blue; }`,
			"Existing",
		);
		const scope = '.pcf-shell-control[data-pcf-control="Existing"]';

		expect(output).toContain(`${scope} .button`);
		expect(output).toContain(`${scope} { color: blue; }`);
	});
});

describe("check-generated-css-scope", () => {
	it("passes scoped PCF CSS and fails unscoped CSS", async () => {
		const passDir = await makeTempDir();
		await fs.writeFile(
			path.join(passDir, "pcf-scoped.css"),
			'.pcf-shell-control[data-pcf-control="Demo"] .button { color: red; }',
			"utf8",
		);

		expect(() =>
			execFileSync(
				"node",
				["scripts/check-generated-css-scope.mjs", passDir],
				{ cwd: repoRoot, stdio: "pipe" },
			),
		).not.toThrow();

		const failDir = await makeTempDir();
		await fs.writeFile(
			path.join(failDir, "pcf-scoped.css"),
			".button { color: red; }",
			"utf8",
		);

		expect(() =>
			execFileSync(
				"node",
				["scripts/check-generated-css-scope.mjs", failDir],
				{ cwd: repoRoot, stdio: "pipe" },
			),
		).toThrow();
	});
});
