import postcss from "postcss";

export const PCF_SCOPED_CSS_FILE = "pcf-scoped.css";

export function scopeCssForPcf(
	css: string,
	controlName: string,
): string {
	const scopeSelector = `.pcf-shell-control[data-pcf-control="${escapeCssAttributeValue(controlName)}"]`;
	const root = postcss.parse(css);

	root.walkRules((rule) => {
		if (isKeyframesRule(rule)) {
			return;
		}

		rule.selector = scopeSelectorList(rule.selector, scopeSelector);
	});

	return [
		"/* Generated by create-ec-app. CSS selectors are scoped to this PCF control. */",
		root.toString(),
	].join("\n");
}

export const scopeCssVariablesForPcf = scopeCssForPcf;

function isKeyframesRule(rule: postcss.Rule): boolean {
	let parent = rule.parent as postcss.Node | undefined;

	while (parent) {
		if (parent.type === "atrule") {
			const atRule = parent as postcss.AtRule;
			if (atRule.name.toLowerCase().endsWith("keyframes")) {
				return true;
			}
		}

		parent = parent.parent as postcss.Node | undefined;
	}

	return false;
}

function scopeSelectorList(selectorList: string, scopeSelector: string): string {
	const scopedSelectors = new Set<string>();

	for (const selector of splitSelectorList(selectorList)) {
		for (const scopedSelector of scopeSingleSelector(selector, scopeSelector)) {
			scopedSelectors.add(scopedSelector);
		}
	}

	return [...scopedSelectors].join(", ");
}

function scopeSingleSelector(
	selector: string,
	scopeSelector: string,
): string[] {
	const normalized = selector.trim();

	if (normalized.includes(scopeSelector)) {
		return [normalized];
	}

	if (
		normalized === ":root" ||
		normalized === ":host" ||
		normalized === "html" ||
		normalized === "body" ||
		normalized === "[data-ec-app-root]" ||
		/^\.ec-app(?:\[.*?\])?$/.test(normalized)
	) {
		return [scopeSelector];
	}

	if (normalized === "*") {
		return [scopeSelector, `${scopeSelector} *`];
	}

	if (
		normalized === ".dark" ||
		/^\.ec-app(?:\[.*?\])?\.dark$/.test(normalized)
	) {
		return [`${scopeSelector}.dark`, `${scopeSelector} .dark`];
	}

	if (normalized.startsWith(".dark ")) {
		const darkDescendant = normalized.slice(".dark".length);
		return [
			`${scopeSelector}.dark${darkDescendant}`,
			`${scopeSelector} .dark${darkDescendant}`,
		];
	}

	const appDarkDescendant = normalized.match(/^\.ec-app(?:\[.*?\])?\s+\.dark(.*)$/);
	if (appDarkDescendant) {
		const darkDescendant = appDarkDescendant[1] as string;
		return [
			`${scopeSelector}.dark${darkDescendant}`,
			`${scopeSelector} .dark${darkDescendant}`,
		];
	}

	return [`${scopeSelector} ${normalized}`];
}

function splitSelectorList(selectorList: string): string[] {
	const selectors: string[] = [];
	let start = 0;
	let nesting = 0;
	let quote: string | null = null;
	let escaped = false;

	for (let index = 0; index < selectorList.length; index += 1) {
		const char = selectorList[index];

		if (escaped) {
			escaped = false;
			continue;
		}

		if (char === "\\") {
			escaped = true;
			continue;
		}

		if (quote) {
			if (char === quote) {
				quote = null;
			}
			continue;
		}

		if (char === '"' || char === "'") {
			quote = char;
			continue;
		}

		if (char === "(" || char === "[") {
			nesting += 1;
			continue;
		}

		if (char === ")" || char === "]") {
			nesting = Math.max(0, nesting - 1);
			continue;
		}

		if (char === "," && nesting === 0) {
			selectors.push(selectorList.slice(start, index).trim());
			start = index + 1;
		}
	}

	selectors.push(selectorList.slice(start).trim());
	return selectors.filter(Boolean);
}

function escapeCssAttributeValue(value: string): string {
	return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
